SELECT * FROM (SELECT * FROM NOTICE ORDER BY REGDATE DESC) WHERE ROWNUM BETWEEN 1 AND 10;

SELECT * FROM NOTICE WHERE CODE=7;

SELECT NVL(MAX(TO_NUMBER(CODE),0)+1 AS CODE FROM NOTICE;

SELECT CODE FROM NOTICE;

SELECT * FROM NOTICE;

INSERT INTO NOTICE(CODE,TITLE,WRITER,CONTENT,REGDATE,HIT) VALUES(?,'A','newlec','c',SYSTIMESTAMP,0);

UPDATE NOTICE SET TITLE=?,CONTENT=? WHERE CODE = ?;

SELECT * FROM "COMMENT";

DROP VIEW NOTICE_VIEW;


--CREATE VIEW NOTICE_VIEW
--AS 
---SELECT ROWNUM NUM, N.* FROM
--(
  -- SELECT N.CODE, N.TITLE, N.WRITER, N.CONTENT, N.REGDATE, N.HIT, M.NAME WRITER_NAME, COUNT(C.CODE) CMT_CNT 
 --  FROM
    --  MEMBER M
    --  RIGHT OUTER JOIN NOTICE N ON M.MID = N.WRITER
    --  LEFT OUTER JOIN "COMMENT" C ON N.CODE = C.NOTICE_CODE
  -- GROUP BY N.CODE, N.TITLE, N.WRITER, N.CONTENT, N.REGDATE, N.HIT, M.NAME
  -- ORDER BY N.REGDATE DESC
--) N


CREATE VIEW NOTICE_VIEW
AS 
SELECT * FROM
(
   SELECT N.CODE, N.TITLE, N.WRITER, N.CONTENT, N.REGDATE, N.HIT, M.NAME WRITER_NAME, COUNT(C.CODE) CMT_CNT 
   FROM
      MEMBER M
      RIGHT OUTER JOIN NOTICE N ON M.MID = N.WRITER
      LEFT OUTER JOIN "COMMENT" C ON N.CODE = C.NOTICE_CODE
   GROUP BY N.CODE, N.TITLE, N.WRITER, N.CONTENT, N.REGDATE, N.HIT, M.NAME
   ORDER BY N.REGDATE DESC
) N

--CREATE VIEW NOTICE_VIEW
--AS
--SELECT ROWNUM NUM, N.* FROM(
--SELECT N.CODE,N.TITLE,N.WRITER,N.CONTENT,N.REGDATE,N.HIT,M.NAME WRITER_NAME, COUNT(C.NOTICE_CODE) CMT_CNT FROM MEMBER M
--RIGHT OUTER JOIN NOTICE N ON M.MID = N.WRITER
--LEFT OUTER JOIN "COMMENT" C ON N.CODE = C.NOTICE_CODE
--GROUP BY N.CODE,N.TITLE,N.WRITER,N.CONTENT,N.REGDATE,N.HIT,M.NAME
--ORDER BY N.REGDATE DESC) N;
--ORDER BY TO_NUMBER(N.CODE) DESC;


SELECT * FROM NOTICE_VIEW;

GROUP BY N.CODE,N.TITLE,N.WRITER,N.CONTENT,N.REGDATE,N.HIT,M.NAME ORDER BY N.REGDATE DESC;

SELECT * FROM (SELECT ROWNUM NUM,NOTICE_VIEW.* FROM NOTICE_VIEW WHERE TITLE LIKE '%%') 
WHERE NUM BETWEEN 11 AND 20;

SELECT * FROM (SELECT ROWNUM NUM,NOTICE_VIEW.* FROM NOTICE_VIEW WHERE TITLE LIKE '%%') 
WHERE CODE = ;



